#!/usr/bin/env node
// Stamp a build id into the four places that have to agree.
//
// Run before pushing. `main` is what GitHub Pages serves, so pushing is
// publishing, and a player whose browser is holding the last build has no way
// of knowing — that is what this exists to fix.
//
//   node tools/stamp-version.mjs
//   node tools/stamp-version.mjs --check     # fail if the stamps disagree
//
// Writes:
//   src/version.js   compiled into the running code, so it names the build a
//                    player is actually looking at
//   version.json     fetched at runtime with no-store, so it names the build
//                    that is deployed right now
//   index.html       ?v= on the entry module and on the stylesheet
//
// The build id is a timestamp rather than a commit SHA, because this runs
// *before* the commit it belongs to exists — a SHA here would always name the
// previous commit, which is worse than useless on a page whose job is to tell
// you what you are running.

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const versionJsPath = join(ROOT, 'src/version.js');
const versionJsonPath = join(ROOT, 'version.json');
const indexPath = join(ROOT, 'index.html');

// Only act when run as a program. `readStamps` is worth importing — the
// version test uses it — and a script whose body runs at load meant that
// merely reading it restamped the repo as a side effect.
const RUN = !!process.argv[1]
  && import.meta.url === new URL(`file://${process.argv[1]}`).href;
const CHECK = process.argv.includes('--check');

const pad = (n) => String(n).padStart(2, '0');
const buildId = (d) =>
  `${d.getUTCFullYear()}.${pad(d.getUTCMonth() + 1)}.${pad(d.getUTCDate())}`
  + `-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;

/** Pull the four stamps out of the files that carry them. */
export async function readStamps() {
  const js = await readFile(versionJsPath, 'utf8').catch(() => '');
  const json = await readFile(versionJsonPath, 'utf8').catch(() => '');
  const html = await readFile(indexPath, 'utf8');
  let parsed = null;
  try { parsed = JSON.parse(json); } catch { parsed = null; }
  return {
    js: js.match(/export const VERSION = '([^']+)'/)?.[1] ?? null,
    json: parsed?.version ?? null,
    entry: html.match(/src="\.\/src\/main\.js\?v=([^"]+)"/)?.[1] ?? null,
    styles: html.match(/href="\.\/styles\.css\?v=([^"]+)"/)?.[1] ?? null,
  };
}

/** Write one build id into all four places at once. */
export async function stamp(now = new Date()) {
  const version = buildId(now);
  const builtAt = now.toISOString();

  await writeFile(versionJsPath, [
    '// Generated by tools/stamp-version.mjs. Do not edit by hand.',
    '//',
    '// This is compiled into the running code, so it names the build a player',
    '// is actually looking at. version.json names the build that is deployed.',
    '// When the two disagree the page is stale — see src/freshness.js.',
    `export const VERSION = '${version}';`,
    `export const BUILT_AT = '${builtAt}';`,
    '',
  ].join('\n'));

  await writeFile(versionJsonPath, `${JSON.stringify({ version, builtAt }, null, 2)}\n`);

  const html = (await readFile(indexPath, 'utf8'))
    .replace(/href="\.\/styles\.css(\?v=[^"]*)?"/, `href="./styles.css?v=${version}"`)
    .replace(/src="\.\/src\/main\.js(\?v=[^"]*)?"/, `src="./src/main.js?v=${version}"`);
  await writeFile(indexPath, html);

  return version;
}

if (RUN && CHECK) {
  const s = await readStamps();
  const all = Object.values(s);
  const agree = all.every((v) => v && v === all[0]);
  console.log(agree
    ? `stamps agree: ${all[0]}`
    : `stamps disagree — version.js ${s.js}, version.json ${s.json}, `
      + `entry ${s.entry}, styles ${s.styles}`);
  process.exit(agree ? 0 : 1);
} else if (RUN) {
  console.log(`stamped ${await stamp()}`);
}
